apiVersion: apps/v1
kind: Deployment

metadata:
  name: loan-service
  namespace: qa-lab

spec:
  replicas: 3

  selector:
    matchLabels:
      app: loan-service

  template:
    metadata:
      labels:
        app: loan-service

    spec:
      containers:
        - name: loan-service

          image: k3d-qa-registry:5000/loan-service:1.0

          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: loan-service-config

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
